---
sidebar_position: 10
---

# T·∫°o exception filter cho app

- Tr∆∞·ªõc ƒë√≥, ta ƒë√£ bi·∫øt t·∫°o 1 [Catch All Exception Filter](./nestjs-fundamentals/exception-filters#catch-all-exception), gi·ªù ta s·∫Ω t·∫°o n√≥ ƒë·ªÉ x·ª≠ l√Ω t·∫•t c·∫£ c√°c exception ƒë∆∞·ª£c throw ra trong app m·ªôt c√°ch c√≥ hi·ªáu qu·∫£.
- Exception filter ta s·∫Ω t·∫°o d∆∞·ªõi ƒë√¢y s·∫Ω:
  - Tr·∫£ v·ªÅ error cho client g·ªìm 3 tr∆∞·ªùng c·ªë ƒë·ªãnh: **statusCode**, **message**, **path**, **details** (c√≥ th·ªÉ `null`), v√† c√≥ th·ªÉ c√≥ th√™m c√°c tr∆∞·ªùng t√πy ch·ªânh kh√°c.
  - N·∫øu m√£ l·ªói tr·∫£ v·ªÅ l√† 500, th√¨ s·∫Ω tr·∫£ v·ªÅ cho client c√≥ d·∫°ng sau, v√† ·ªü server s·∫Ω log ra chi ti·∫øt l·ªói ƒë√≥:

```json
{
  "statusCode": 500,
  "message": "Internal server error",
  "path": "/api/v1/auth/upload"
}
```

- ƒê·∫ßu ti√™n, t·∫°o **BaseExceptionResponse.dto.ts**:

```ts title="BaseExceptionResponse.dto.ts"
import { Expose } from "class-transformer";

export class BaseExceptionResponse {
  @Expose()
  statusCode: number;

  @Expose()
  message: string;

  @Expose()
  details: any | null;

  @Expose()
  path: string;
}
```

- T·∫°o **all-exception-filter.ts**:

```ts title="all-exception-filter.ts"
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  HttpException,
  HttpStatus,
  Logger,
} from "@nestjs/common";
import { WsException } from "@nestjs/websockets";
import { Request, Response } from "express";
import { Socket } from "socket.io";

import { BaseExceptionResponse } from "src/common/dto/BaseExceptionResponse.dto";

@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  private readonly logger = new Logger(AllExceptionsFilter.name);

  catch(
    exception: WsException | HttpException | Error,
    host: ArgumentsHost
  ): void {
    const contextType = host.getType();

    if (contextType === "http") {
      this.handleHttpException(exception, host);
    } else if (contextType === "ws") {
      this.handleWsException(exception, host);
    }

    const isLoggableException =
      !(exception instanceof WsException) &&
      !(exception instanceof HttpException);

    if (isLoggableException) {
      this.logUnhandledException(exception, host);
    }
  }

  private handleWsException(
    exception: WsException | Error,
    host: ArgumentsHost
  ) {
    const socketClient = host.switchToWs().getClient<Socket>();
    const wsData = host.switchToWs().getData();
    const pattern = host.switchToWs().getPattern();
    const wsError = !(exception instanceof WsException)
      ? "Internal server error"
      : exception.getError();

    const errorDetails =
      wsError instanceof Object ? { ...wsError } : { message: wsError };
    socketClient.emit("ws_exception", {
      ...errorDetails,
      id: socketClient.id,
      pattern,
      data: wsData,
    });
  }

  private handleHttpException(
    exception: HttpException | Error,
    host: ArgumentsHost
  ): void {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();

    let statusCode: number = HttpStatus.INTERNAL_SERVER_ERROR;
    let message: string = "Internal server error";
    let responseBody: BaseExceptionResponse = {
      statusCode,
      message,
      path: request.url,
      details: null,
    };

    if (exception instanceof HttpException) {
      statusCode = exception.getStatus();
      if (statusCode !== HttpStatus.INTERNAL_SERVER_ERROR) {
        const exceptionResponseMessage: string | undefined = (
          exception.getResponse() as any
        ).message;
        message = exceptionResponseMessage || "Unknown error message";

        /* 
          - L·∫•y ra c√°c error fields kh√°c m√† ta ƒë√£ th√™m v√†o khi throw exception
          - V√≠ d·ª•: khi ta throw new BadRequestException({ errorType: 'INVALID_CREDENTIALS', message: 'Invalid email' }) th√¨ extraErrorFields = { errorType: 'INVALID_CREDENTIALS', message: 'Invalid email' }
        */
        const { error, ...extraErrorFields } = exception.getResponse() as any;

        responseBody = {
          ...responseBody,
          ...extraErrorFields,
          message,
          statusCode,
        };
      }
    }

    response.status(statusCode).json(responseBody);
  }

  private logUnhandledException(exception: Error, host: ArgumentsHost) {
    const contextType = host.getType();

    if (contextType === "http") {
      const httpCtx = host.switchToHttp();
      const request = httpCtx.getRequest<Request>();
      this.logger.error(
        `\nüëâ Context type: ${contextType.toUpperCase()}\nüëâ Method: ${
          request.method
        }\nüëâ Path: ${request.url}\nüëâ Details: ${exception.stack?.toString()}`
      );
    } else if (contextType === "ws") {
      const wsCtx = host.switchToWs();
      const pattern = wsCtx.getPattern();
      this.logger.error(
        `\nüëâ Context type: ${contextType.toUpperCase()}\nüëâ Pattern: ${pattern}\nüëâ Details: ${exception.stack?.toString()}`
      );
    }
  }
}
```

- Cu·ªëi c√πng, ·ªü file **app.module.ts**:

```ts title="app.module.ts"
import { APP_FILTER } from "@nestjs/core";

@Module({
  providers: [{ provide: APP_FILTER, useClass: AllExceptionsFilter }],
})
export class AppModule {}
```

:::caution

- N·∫øu truy·ªÅn 1 object khi throw exception (ho·∫∑c custom exception). H√£y nh·ªõ lu√¥n th√™m tr∆∞·ªùng "message". ƒêi·ªÅu n√†y l√† b·∫Øt bu·ªôc.

```ts
// ‚ùå Kh√¥ng h·ª£p l·ªá
throw new BadRequestException({
  errorType: ELoginExceptionErrorType.INVALID_2FA_OTP,
});

// ‚úÖ H·ª£p l·ªá
throw new BadRequestException({
  message: "Two factor authenticator code is invalid",
  errorType: ELoginExceptionErrorType.INVALID_2FA_OTP,
});

// ‚úÖ H·ª£p l·ªá b·ªüi v√¨ truy·ªÅn 1 string th√¨ NestJS t·ª± g√°n n√≥ l√† thu·ªôc t√≠nh "message"
throw new BadRequestException("Two factor authenticator code is invalid");
```

:::
